export default [
    {id: 0, nome: "JORNALISMO", descricao: "Profissional responsável por buscar, investigar, redigir e transmitir notícias.", link: "https://guiadoestudante.abril.com.br/profissoes/jornalismo/"},
    {id: 1, nome: "CIÊNCIAS NATURAIS E EXATAS", descricao: "Leciona Física, Química, Biologia, Matemática.", link: "https://guiadoestudante.abril.com.br/profissoes/ciencias-naturais-e-exatas/"},
    {id: 2, nome: "PSICOPEDAGOGIA", descricao: "Identifica e trata as dificuldades de aprendizagem.", link: "https://guiadoestudante.abril.com.br/profissoes/psicopedagogia/"},
    {id: 3, nome: "FOTOGRAFIA", descricao: "Obtenção e processamento de imagem.", link: "https://www.guiadacarreira.com.br/cursos/faculdade-de-fotografia/"},
    {id: 4, nome: "CIÊNCIAS ATUARIAIS", descricao: "Análise de riscos e expectativas nas áreas de seguros e fundos de pensão.", link: "htps://www.guiadacarreira.com.br/guia-das-profissoes/ciencias-atuarias/"},
    {id: 5, nome: "QUÍMICA INDUSTRIAL", descricao: "Transforma matéria-prima em produtos químicos industriais.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/quimica-industrial"},
    {id: 6, nome: "DESIGN DE GAMES", descricao: "Cria e jogos eletrônicos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/design-de-games"},
    {id: 7, nome: "GEOGRAFIA", descricao: "Estuda os fenômenos Físicos, Biológicos e Humanos que ocorrem na Terra.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/geografia/"},
    {id: 8, nome: "CIÊNCIAS HUMANAS", descricao: "Leciona História, Geografia, Filosofia e Sociologia.", link: "https://www2.ufjf.br/ufjf/ensino/graduacao/ciencias-humanas/"},
    {id: 9, nome: "COMUNICAÇÃO ASSISTIVA", descricao: "Tradução e interpretações em Libras e Braille.", link: "https://vestibular.brasilescola.uol.com.br/guia-de-profissoes/comunicacao-assistiva.htm"},
    {id: 10, nome: "CIÊNCIA E TECNOLOGIA", descricao: "Estuda Ciências Exatas, Computação, Princípios de Engenharia.", link: "https://guiadoestudante.abril.com.br/profissoes/ciencia-e-tecnologia/#:~:text=O%20bacharel%20em%20Ci%C3%AAncia%20e,nos%20princ%C3%ADpios%20b%C3%A1sicos%20das%20engenharias."},
    {id: 11, nome: "ARTES E DESIGN", descricao: "Artes Visuais, Design, Moda, Cinema, Áudio Visuais.", link: "https://www.ufjf.br/biad/o-curso/"},
    {id: 12, nome: "PAISAGISMO", descricao: "Projetos de espaços livres como jardins, parques e praças.", link: "https://www.guiadacarreira.com.br/cursos/paisagismo/"},
    {id: 13, nome: "OBSTETRÍCIA", descricao: "Cuidados com gestantes, parturientes e recém-nascidos.", link: "https://www.guiadacarreira.com.br/cursos/obstetricia/"},
    {id: 14, nome: "DECORAÇÃO", descricao: "Elaborar e executar Projetos de organização de ambientes.", link: "https://www.guiadacarreira.com.br/profissao/design-de-interiores-2/"},
    {id: 15, nome: "OPTOMETRIA", descricao: "Identificar problemas de acuidade visual.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/optometria/"},
    {id: 16, nome: "MULTIMÍDIA", descricao: "Criar comunicações por meios digitais.", link: "https://www.guiadacarreira.com.br/cursos/multimidia/"},
    {id: 17, nome: "OCEANOGRAFIA", descricao: "Estudar a fauna, flora e características dos oceanos, rios e lagos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/oceanografia/"},
    {id: 18, nome: "ODONTOLOGIA", descricao: "Tratamento dos dentes, da boca e dos ossos da face.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/odontologia/"},
    {id: 19, nome: "MARKETING", descricao: "Planejar estratégias para melhorar a competitividade de um produto no mercado.", link: "https://www.guiadacarreira.com.br/cursos/faculdade-de-marketing/"},
    {id: 20, nome: "BIBLIOTECONOMIA", descricao: "Organizar e gerenciar bibliotecas.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/biblioteconomia/"},
    {id: 21, nome: "ADMINISTRAÇÃO DE EMPRESAS", descricao: "Gerenciar recursos humanos, materiais e financeiros.", link: "https://guiadoestudante.abril.com.br/profissoes/administracao/"},
    {id: 22, nome: "DIREITO", descricao: "Aplicar as Leis e Normas Jurídicas.", link: "https://www.guiadacarreira.com.br/cursos/curso-direito/"},
    {id: 23, nome: "ADMINISTRAÇÃO HOSPITALAR", descricao: "Gerenciar Hospitais e Clínicas.", link: "https://www.guiadacarreira.com.br/cursos/gestao-hospitalar-2/"},
    {id: 24, nome: "ESTUDOS LITERÁRIOS", descricao: "Estudar os gêneros literários.", link: "http://www.upa.unicamp.br/estudos-literarios"},
    {id: 25, nome: "LETRAS", descricao: "Estudar a Língua Portuguesa e outros idiomas.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/letras/"},
    {id: 26, nome: "MUSEOLOGIA", descricao: "Classificação, Conservação e Exposição de Artes.", link: "https://www.guiadacarreira.com.br/profissao/museologia/"},
    {id: 27, nome: "ARTES PLÁSTICAS", descricao: "Criação de desenhos, pinturas, esculturas, etc.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/artes-plasticas/"},
    {id: 28, nome: "EDUCAÇÃO ARTÍSTICA", descricao: "Ensinar Artes em geral.", link: "https://querobolsa.com.br/cursos-e-faculdades/educacao-artistica"},
    {id: 29, nome: "PSICOLOGIA", descricao: "Estudar os fenômenos psíquicos e de comportamento.", link: "https://www.guiadacarreira.com.br/carreira/psicologia/"},
    {id: 30, nome: "RELAÇÕES PÚBLICAS", descricao: "Promover a imagem de uma empresa ou uma marca.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/relacoes-publicas/"},
    {id: 31, nome: "CINEMA", descricao: "Criação e produção de filmes, séries e vídeos.", link: "https://www.guiadacarreira.com.br/cursos/faculdade-de-cinema/"},
    {id: 32, nome: "AERONÁUTICA", descricao: "Carreira Militar.", link: "https://institutoibpm.com.br/como-seguir-carreira-na-aeronautica/"},
    {id: 33, nome: "DESIGN DE INTERIORES", descricao: "Projetar ambientes, com estética e funcionalidade.", link: "https://www.guiadacarreira.com.br/profissao/design-de-interiores-2/#:~:text=J%C3%A1%20no%20curso%20superior%20de,dura%C3%A7%C3%A3o%20m%C3%A9dia%20de%202%20anoss"},
    {id: 34, nome: "GESTÃO SERVIÇOS DE SAÚDE", descricao: "Administrar Serviços e Sistemas na área de saúde.", link: "https://www.uninove.br/cursos/mba/presencial/gestao-em-servicos-de-saude"},
    {id: 35, nome: "QUIROPRAXIA", descricao: "Terapia Manual (Massagem).", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/quiropraxia/"},
    {id: 36, nome: "GESTÃO DA INFORMAÇÃO", descricao: "Coletar, processar e distribuir Informações em empresas.", link: "https://querobolsa.com.br/cursos-e-faculdades/gestao-da-informacao"},
    {id: 37, nome: "COMUNICAÇÃO SOCIAL", descricao: "Estudar os processos de comunicação (Jornalismo, Publicidade, Relações Públicas).", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/comunicacao-social/"},
    {id: 38, nome: "TEOLOGIA", descricao: "Estudar as Religiões e Doutrinas.", link: "https://www.guiadacarreira.com.br/profissao/teologia/"},
    {id: 39, nome: "SEGURANÇA PÚBLICA", descricao: "Programas e Políticas que visem a redução da violência.", link: "https://www.guiadacarreira.com.br/cursos/seguranca-publica/"},
    {id: 40, nome: "DESIGN DE MODA", descricao: "Desenhar roupas, estampas e acessórios.", link: "https://www.guiadacarreira.com.br/cursos/design-de-moda/"},
    {id: 41, nome: "ESTÉTICA E COSMÉTICA", descricao: "Beleza, Saúde e Bem Estar.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/estetica/"},
    {id: 42, nome: "GESTÃO HOSPITALAR", descricao: "Gerenciar Hospitais e Serviços de Saúde.", link: "https://www.guiadacarreira.com.br/cursos/gestao-hospitalar-2/"},
    {id: 43, nome: "CIÊNCIAS DO ESPORTE", descricao: "Treinamento, preparação física de indivíduos e equipes e gestão esportiva.", link: "https://vestibular.mundoeducacao.uol.com.br/guia-de-profissoes/ciencias-esporte.htm"},
    {id: 44, nome: "ARTES VISUAIS", descricao: "Estudar as formas de artes (Pinturas, Esculturas, Desenhos, etc).", link: "https://www.guiadacarreira.com.br/carreira/artes-visuais/"},
    {id: 45, nome: "ANTROPOLOGIA", descricao: "Estudar a origem, evolução, características, costumes humanos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/antropologia/"},
    {id: 46, nome: "EXÉRCITO", descricao: "Carreira Militar.", link: "http://www.eb.mil.br/web/ingresso/militar-de-carreira"},
    {id: 47, nome: "MUSICOTERAPIA", descricao: "Utilizar a música e seus elementos para tratamentos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/musicoterapia/"},
    {id: 48, nome: "ARQUEOLOGIA", descricao: "Estudar as culturas e sociedades a partir de vestígios.", link: "https://guiadoestudante.abril.com.br/profissoes/arqueologia/"},
    {id: 49, nome: "PRODUÇÃO CULTURAL", descricao: "Organizar e executar projetos culturais e eventos.", link: "https://www.guiadacarreira.com.br/profissao/producao-cultural/"},
    {id: 50, nome: "DESIGN GRÁFICO", descricao: "Criar Logotipos, panfletos, outdoor, etc.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/design-grafico/"},
    {id: 51, nome: "TERAPIA OCUPACIONAL", descricao: "Reabilitação Física e Mental através de atividades diversas.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/terapia-ocupacional/sas"},
    {id: 52, nome: "EDUCAÇÃO FÍSICA", descricao: "Promoção da saúde através de atividades físicas.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/educacao-fisica/"},
    {id: 53, nome: "COMÉRCIO EXTERIOR", descricao: "Compra e venda entre empresas de países diversos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/comercio-exterior/"},
    {id: 54, nome: "GESTÃO DE QUALIDADE", descricao: "Controle da qualidade de produtos e serviços.", link: "https://querobolsa.com.br/cursos-e-faculdades/gestao-da-qualidade"},
    {id: 55, nome: "FÍSICA", descricao: "Estudo da matéria e suas propriedades.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/fisica/"},
    {id: 56, nome: "ESTUDOS DE MÍDIA", descricao: "Estuda os diferentes meios de comunicação.", link: "https://guiadoestudante.abril.com.br/profissoes/estudos-de-midia/"},
    {id: 57, nome: "LINGUÍSTICA", descricao: "Estuda a linguagem verbal, a gramática e evolução dos idiomas.", link: "https://guiadoestudante.abril.com.br/profissoes/linguistica/"},
    {id: 58, nome: "METEOROLOGIA", descricao: "Estuda a atmosfera e os fenômenos da terra.", link: "https://www.guiadacarreira.com.br/carreira/meteorologia/"},
    {id: 59, nome: "ESTATÍSTICA", descricao: "Método para analisar dados.", link: "https://guiadoestudante.abril.com.br/profissoes/estatistica/"},
    {id: 60, nome: "ESTUDOS SOCIAIS", descricao: "Lecionar Geografia e História.", link: "https://www.curso-objetivo.br/vestibular/carreiras_profissoes/estudos_sociais.aspx"},
    {id: 61, nome: "ENFERMAGEM", descricao: "Assistência e cuidados com os enfermos.", link: "https://guiadoestudante.abril.com.br/profissoes/enfermagem/"},
    {id: 62, nome: "DESENHO INDUSTRIAL", descricao: "Criar desenhos de diversos produtos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/desenho-industrial/#:~:text=O%20profissional%20formado%20em%20Desenho,aspectos%20construtivos%20e%20de%20est%C3%A9tica"},
    {id: 63, nome: "GERONTOLOGIA", descricao: "Estudar o processo de envelhecimento humano.", link: "https://www.guiadacarreira.com.br/profissao/gerontologia/#:~:text=Ao%20contr%C3%A1rio%20do%20que%20muitos,vida%20ao%20longo%20dos%20anos"},
    {id: 64, nome: "NUTRIÇÃO", descricao: "Promover saúde por meio da alimentação.", link: "https://www.guiadacarreira.com.br/carreira/nutricao/"},
    {id: 65, nome: "NATUROLOGIA APLICADA", descricao: "Aplicar métodos naturais para promover a saúde humana.", link: "https://guiadoestudante.abril.com.br/profissoes/naturologia"},
    {id: 66, nome: "FILOSOFIA", descricao: "Estudar a essência e a natureza do Universo e do Homem.", link: "https://guiadoestudante.abril.com.br/profissoes/filosofia/"},
    {id: 67, nome: "CIÊNCIAS CONTÁBEIS", descricao: "Registrar e controlar as receitas, despesas e lucros de uma empresa.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/ciencias-contabeis/"},
    {id: 68, nome: "CIÊNCIAS DE ALIMENTOS", descricao: "Estuda o teor nutricional dos alimentos.", link: "https://www.guiadacarreira.com.br/profissao/ciencia-e-tecnologia-de-alimentos/"},
    {id: 69, nome: "HISTÓRIA", descricao: "Estudar o passado da humanidade e sua evolução.", link: "https://www.guiadacarreira.com.br/cursos/licenciatura-historia/"},
    {id: 70, nome: "CIÊNCIA DO ESTADO E  GOVERNANÇA SOCIAL", descricao: "Planejar executar as políticas públicas.", link: "https://viacarreira.com/ciencias-do-estado/"},
    {id: 71, nome: "CIÊNCIAS SOCIAIS", descricao: "Estudar a origem e organização da sociedade.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/ciencias-sociais/"},
    {id: 72, nome: "ZOOTECNIA", descricao: "Aprimorar produtividade na criação de animais e de produtos.", link: "https://guiadoestudante.abril.com.br/profissoes/zootecnia/"},
    {id: 73, nome: "FISIOTERAPIA", descricao: "Prevenção e tratamento de doenças e lesões.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/fisioterapia/"},
    {id: 74, nome: "QUÍMICA", descricao: "Estuda a composição, estrutura e propriedade da matéria.", link: "https://guiadoestudante.abril.com.br/profissoes/quimica/"},
    {id: 75, nome: "QUÍMICA TECNOLÓGICA", descricao: "Pesquisar e controlar as operação de processos industriais.", link: "https://www.iq.unesp.br/#!/graduacao1260/cursos/bacharelado-em-quimica-tecnologica/"},
    {id: 76, nome: "FONOAUDIOLOGIA", descricao: "Estudo e tratamento da fonação e da audição.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/fonoaudiologia/"},
    {id: 77, nome: "MANUTENÇÃO DE AERONAVES", descricao: "Instalação e manutenção de equipamentos de aeronaves.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/manutencao-de-aeronaves/"},
    {id: 78, nome: "AGRONEGÓCIOS E ADM. RURAL", descricao: "Gerenciar empresas do agronegócio.", link: "http://www.faculdade.cnabrasil.org.br/cursos/tecnologia-em-gestao-do-agronegocio/"},
    {id: 79, nome: "GESTÃO COMERCIAL", descricao: "Gerenciar processos de compra e venda de produtos.", link: "https://www.guiadacarreira.com.br/cursos/gestao-comercial/"},
    {id: 80, nome: "HOTELARIA", descricao: "Gerenciar os serviços de hotéis. Resorts, etc.", link: "https://guiadoestudante.abril.com.br/profissoes/hotelaria/"},
    {id: 81, nome: "GESTÃO DE LOGÍSTICA", descricao: "Compras, armazenamento e distribuição de produtos", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/logistica/"},
    {id: 82, nome: "SERVIÇO SOCIAL", descricao: "Melhorar a qualidade de vida e combater as desigualdades.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/servico-social/"},
    {id: 83, nome: "GEOLOGIA", descricao: "Estuda a origem, estrutura e composição da crosta terrestre.", link: "https://guiadoestudante.abril.com.br/profissoes/geologia/"},
    {id: 84, nome: "PUBLICIDADE E PROPAGANDA", descricao: "Criação de campanhas e peças publicitárias.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/publicidade-propaganda/"},
    {id: 85, nome: "AQUACULTURA", descricao: "Produção de organismos aquáticos para consumo.", link: "https://www.guiadacarreira.com.br/cursos/aquicultura/"},
    {id: 86, nome: "CIÊNCIAS AGRÁRIAS", descricao: "Aprimorar a produção agropecuária e preservar os recursos naturais.", link: "https://www.guiadacarreira.com.br/profissao/ciencias-agrarias/"},
    {id: 87, nome: "MATEMÁTICA COMPUTACIONAL", descricao: "Modelagem matemática e desenvolvimento de algoritmos para a computação.", link: "https://www.algosobre.com.br/guia-de-profissoes/matematica-computacional.html"},
    {id: 88, nome: "TECNOLOGIA TÊXTIL", descricao: "Produção de tecidos e estilismo.", link: "https://www.guiadacarreira.com.br/profissao/producao-textil/"},
    {id: 89, nome: "TURISMO", descricao: "Organização de viagens e eventos.", link: "https://www.guiadacarreira.com.br/cursos/graduacao-curso-de-turismo/"},
    {id: 90, nome: "LICENCIATURA EM EDUCAÇÃO NO  CAMPO", descricao: "Professor nas áreas rurais.", link: "https://www.ufrgs.br/liceducampofaced/o-curso/"},
    {id: 91, nome: "LICENCIATURA INTERCULTURAL  INDÍGENA", descricao: "Lecionar em escolas indígenas.", link: "https://www.ufpe.br/interculturalindigenacaa"},
    {id: 92, nome: "MATEMÁTICA", descricao: "Estudar espaços, relações abstratas e lógicas.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/matematica/"},
    {id: 93, nome: "INFORMÁTICA BIOMÉDICA", descricao: "Desenvolve softwares e equipamentos para a área biológica e médica.", link: "https://www.guiadacarreira.com.br/profissao/informatica-biomedica/"},
    {id: 94, nome: "BIOTECNOLOGIA", descricao: "Desenvolvimento de organismos geneticamente modificados.", link: "https://www.infoescola.com/biologia/biotecnologia/"},
    {id: 95, nome: "TECNOLOGIA DE LATICÍNIOS", descricao: "Industrialização do leite e seus derivados.", link: "https://vestibular.mundoeducacao.uol.com.br/guia-de-profissoes/tecnologia-laticinios.htm"},
    {id: 96, nome: "FARMÁCIA", descricao: "Estudar e produzir alimentos, medicamentos, cosméticos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/farmacia/"},
    {id: 97, nome: "TRADUÇÃO E INTERPRETAÇÃO", descricao: "Transposição de textos e falas de um idioma para outro.", link: "https://guiadoestudante.abril.com.br/profissoes/tradutor-e-interprete/"},
    {id: 98, nome: "PRODUÇÃO EDITORIAL", descricao: "Edição e publicação de obras impressas e eletrônicas.", link: "https://www.guiadacarreira.com.br/profissao/producao-editorial/"},
    {id: 99, nome: "CONSERVAÇÃO E RESTAURAÇÃO", descricao: "Restaurar obras de artes, documentos e livros.", link: "https://guiadoestudante.abril.com.br/profissoes/conservacao-e-restauro/"},
    {id: 100, nome: "PEDAGOGIA", descricao: "Ciência da Educação, Ensino e Aprendizagem.", link: "https://guiadoestudante.abril.com.br/profissoes/pedagogia/"},
    {id: 101, nome: "CIÊNCIAS ECONÔMICAS", descricao: "Estudar a produção, distribuição, consumo de bens e serviços.", link: "https://guiadoestudante.abril.com.br/profissoes/ciencias-economicas/"},
    {id: 102, nome: "CINEMA DE ANIMAÇÃO E ARTES DIGITAIS", descricao: "Produzir animações, jogos, filmes e mídias publicitárias.", link: "https://guiadoestudante.abril.com.br/profissoes/cinema-e-audiovisual/"},
    {id: 103, nome: "BIOMEDICINA", descricao: "Pesquisar microorganismos, medicamentos e vacinas.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/biomedicina/"},
    {id: 104, nome: "ARTES CÊNICAS", descricao: "Criação, montagem e interpretação de espetáculos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/artes-cenicas/"},
    {id: 105, nome: "MEDICINA", descricao: "Prevenção, diagnóstico e tratamento da saúde.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/carreira-medicina/"},
    {id: 106, nome: "ECONOMIA DOMÉSTICA", descricao: "Implantar programas de economia familiar.", link: "https://www.guiadacarreira.com.br/profissao/economia-domestica/"},
    {id: 107, nome: "GESTÃO DE TECNOLOGIA DA INFORMAÇÃO", descricao: "Implementar sistemas informatizados.", link: "https://www.guiadacarreira.com.br/carreira/gestao-da-tecnologia-da-informacao/"},
    {id: 108, nome: "GESTÃO DE RH", descricao: "Gerenciar áreas de seleção, recrutamento, treinamento, etc.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/gestao-recursos-humanos/"},
    {id: 109, nome: "DANÇA", descricao: "Criar espetáculos de dança, musicais e coreografias.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/danca/"},
    {id: 110, nome: "COMUNICAÇÃO DAS ARTES DO CORPO", descricao: "Criar espetáculos de dança, teatro, circo e performances.", link: "https://www.guiadacarreira.com.br/cursos/artes-do-corpo/"},
    {id: 111, nome: "RADIO E TV", descricao: "Criação, Produção de conteúdos audiovisuais.", link: "https://www.guiadacarreira.com.br/cursos/curso-radio-e-tv/"},
    {id: 112, nome: "MÚSICA", descricao: "Compor, interpretar, reger e produz obras musicais.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/musica-profissao/"},
    {id: 113, nome: "CIÊNCIAS BIOMÉDICAS", descricao: "Pesquisar, diagnósticar doenças e tratamentos.", link: "https://www.universia.net/br/actualidad/orientacao-academica/conhecendo-o-curso-ciencias-biomedicas-1165660.html"},
    {id: 114, nome: "DIPLOMACIA", descricao: "Representar o Brasil junto a outros Países.", link: "http://www.institutoriobranco.itamaraty.gov.br/curso-de-formacao"},
    {id: 115, nome: "MEDICINA VETERINÁRIA", descricao: "Cuidar da saúde, alimentação e reprodução de animais.", link: "https://guiadoestudante.abril.com.br/profissoes/medicina-veterinaria/"},
    {id: 116, nome: "ECOLOGIA", descricao: "Estudar a relação entre o homem e a natureza.", link: "https://guiadoestudante.abril.com.br/profissoes/ecologia/"},
    {id: 117, nome: "CIÊNCIAS AERONÁUTICAS", descricao: "Pilotar aeronaves, gerenciar aeroportos e empresas de aviação.", link: "https://www.guiadacarreira.com.br/profissao/ciencias-aeronauticas/"},
    {id: 118, nome: "CIÊNCIA DA COMPUTAÇÃO", descricao: "Elaboração de programas de informática.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/ciencia-da-computacao/"},
    {id: 119, nome: "GESTÃO AMBIENTAL", descricao: "Estudar o uso adequado dos recursos naturais.", link: "https://www.guiadacarreira.com.br/cursos/curso-de-gestao-ambiental/"},
    {id: 120, nome: "SISTEMAS DE INFORMAÇÕES", descricao: "Sistemas computacionais para fluxo das informações.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/sistemas-informacao/"},
    {id: 121, nome: "CIÊNCIAS SÓCIO-AMBIENTAIS", descricao: "Estudar a relação entre a sociedade e o ambiente.", link: "https://ufmg.br/cursos/graduacao/2385/91070#:~:text=O%20curso%20de%20Ci%C3%AAncias%20Socioambientais,rela%C3%A7%C3%B5es%20entre%20sociedades%20e%20ambientes"},
    {id: 122, nome: "CONTROLADORIA E FINANÇAS", descricao: "Planejar e controlar a área financeira de uma empresa.", link: "https://www.face.ufmg.br/graduacao/controladoria-e-financas/o-curso.html"},
    {id: 123, nome: "GESTÃO PÚBLICA", descricao: "Atuar na administração de órgãos e serviços públicos.", link: "https://www.guiadacarreira.com.br/cursos/gestao-publica/"},
    {id: 124, nome: "CIÊNCIAS BIOLÓGICAS", descricao: "Estudar os seres vivos e sua relação com o ambiente.", link: "https://www.guiadacarreira.com.br/cursos/ciencias-biologicas/"},
    {id: 125, nome: "ARQUITETURA", descricao: "Projetar e desenhar edificações, espaços urbanos.", link: "https://guiadoestudante.abril.com.br/profissoes/arquitetura-e-urbanismo/"},
    {id: 126, nome: "JOGOS DIGITAIS", descricao: "Criação de jogos eletrônicos.", link: "https://www.guiadacarreira.com.br/cursos/jogos-digitais/"},
    {id: 127, nome: "TECNOLOGIA EM RADIOLOGIA E DIAGNÓSTICO POR IMAGEM", descricao: "Operar equipamentos de diagnóstico por imagem.", link: "https://www.guiadacarreira.com.br/cursos/tecnologo-em-radiologia/"},
    {id: 128, nome: "FÍSICA COMPUTACIONAL", descricao: "Utilização de métodos computacionais para resolver problemas da física.", link: "https://www.educamaisbrasil.com.br/enem/fisica/fisica-computacional"},
    {id: 129, nome: "DESIGN DE PRODUTOS", descricao: "Criação e desenvolvimento de produtos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/design-de-produto/"},
    {id: 130, nome: "ADMINISTRAÇÃO PÚBLICA", descricao: "Gerenciamento de instituições públicas.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/curso-administracao-publica/"},
    {id: 131, nome: "SECRETARIADO EXECUTIVO", descricao: "Organizar a rotina de trabalho de um executivo.", link: "https://www.guiadacarreira.com.br/cursos/secretariado-executivo/"},
    {id: 132, nome: "ASTRONOMIA", descricao: "Estudo do universo e corpos celestes.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/astronomia/"},
    {id: 133, nome: "MICROBIOLOGIA E IMUNOLOGIA", descricao: "Estudar microorganismos (vírus e bactérias).", link: "https://www.microbiologia.ufrj.br/portal/index.php/pt/graduacao"},
    {id: 134, nome: "GASTRONOMIA", descricao: "Conhecimento e prática da arte culinária.", link: "https://www.guiadacarreira.com.br/cursos/faculdade-de-gastronomia/"},
    {id: 135, nome: "GESTÃO DE POLÍTICAS PÚBLICAS", descricao: "Gestão das políticas de prestação de serviços para a sociedade.", link: "https://blog.orientu.com.br/cursos/gestao-de-politicas-publicas/"},
    {id: 136, nome: "RELAÇÕES INTERNACIONAIS", descricao: "Condução das relações entre empresas, instituições e países.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/relacoes-internacionais/"},
    {id: 137, nome: "COMUNICAÇÃO VISUAL", descricao: "Criar elementos visuais gráficos na comunicação.", link: "https://www.maisbolsas.com.br/cursos-e-faculdades/design-comunicacao-visual"},
    {id: 138, nome: "CIÊNCIAS DA INFORMAÇÃO", descricao: "Coletar, análisar e disseminar as informações em empresa.", link: "http://www.juventudect.fiocruz.br/categoria-ciencia/ciencias-sociais-aplicadas/ciencia-da-informacao"},
    {id: 139, nome: "CIÊNCIAS AMBIENTAIS", descricao: "Recuperação e preservação do meio ambiente.", link: "https://www.guiadacarreira.com.br/carreira/ciencias-ambientais/"},
    {id: 140, nome: "CIÊNCIA POLÍTICA", descricao: "Estudo da política, estrutura e processos do governo.", link: "https://www.guiadacarreira.com.br/cursos/ciencias-politicas-dia-a-dia-profissional/"},
    {id: 141, nome: "FÍSICA MÉDICA", descricao: "Aplicação da Física na área da saúde (imagens, laser).", link: "https://www2.unesp.br/portal#!/guiadeprofissoes/exatas/fisica-medica/"},
    {id: 142, nome: "GEO-PROCESSAMENTO", descricao: "Coletar e analisar dados de mapas, cartas topográficas.", link: "https://www.guiadacarreira.com.br/profissao/geoprocessamento/"},
    {id: 143, nome: "DEFESA E GESTÃO ESTRATÉGICA INTERNACIONAL", descricao: "Elaborar políticas públicas estratégicas para defesa da sociedade.", link: "https://guiadoestudante.abril.com.br/profissoes/defesa-e-gestao-estrategica-internacional/"},
    {id: 144, nome: "IMAGEM E SOM", descricao: "Produção audiovisual (som, fotografia e animação).", link: "https://www.guiadacarreira.com.br/cursos/producao-audiovisual/"},
    {id: 145, nome: "MARINHA", descricao: "Carreira Militar.", link: "https://www.marinha.mil.br/carreira-militar"},
    {id: 146, nome: "PROCESSOS GERENCIAIS", descricao: "Gestão de processos e serviços.", link: "https://www.guiadacarreira.com.br/cursos/processos-gerenciais/"},
    {id: 147, nome: "DESIGN DE AMBIENTES", descricao: "Projetar espaços internos e externos.", link: "http://www.uemg.br/graduacao/cursos2/course/design-de-ambientes"},
    {id: 148, nome: "DESIGN", descricao: "Desenvolver projetos buscando estética e funcionalidade.", link: "https://querobolsa.com.br/cursos-e-faculdades/design"},
    {id: 149, nome: "LUTERIA", descricao: "Construção e manutenção de instrumentos musicais.", link: "https://guiadoestudante.abril.com.br/profissoes/luteria/"},
    {id: 150, nome: "AGROECOLOGIA", descricao: "Cultivar e manejar os produtos de forma sustentável.", link: "https://guiadoestudante.abril.com.br/profissoes/agroecologia/"},
    {id: 151, nome: "HISTÓRIA DA ARTE", descricao: "Conhecimentos sobre artes, cultura e história.", link: "https://guiadoestudante.abril.com.br/profissoes/historia-da-arte/"},
    {id: 152, nome: "PRODUÇÃO CÊNICA", descricao: "Montagem de espetáculos.", link: "https://www.guiadacarreira.com.br/profissao/producao-cenica/"},
    {id: 153, nome: "PRODUÇÃO FONOGRÁFICA", descricao: "Produção e gravação de músicas, vinhetas e efeitos sonoros.", link: "https://www.guiadacarreira.com.br/profissao/producao-fonografica/"},
    {id: 154, nome: "EDUCAÇÃO ESPECIAL", descricao: "Educação de deficientes.", link: "https://www.guiadacarreira.com.br/cursos/educacao-especial/"},
    {id: 155, nome: "NEGÓCIOS IMOBILIÁRIOS", descricao: "Gerenciar venda, compra e locação de imóveis.", link: "https://querobolsa.com.br/cursos-e-faculdades/negocios-imobiliarios"},
    {id: 156, nome: "AGRONEGÓCIO E AGROPECUÁRIA", descricao: "Administrar negócios do campo.", link: "https://guiadoestudante.abril.com.br/profissoes/agronegocios-e-agropecuaria/"},
    {id: 157, nome: "ANIMAÇÃO", descricao: "Criar animações digitais.", link: "https://guiadoestudante.abril.com.br/profissoes/animacao/"},
    {id: 158, nome: "COOPERATIVISMO", descricao: "Gerenciar cooperativas.", link: "https://guiadoestudante.abril.com.br/profissoes/cooperativismo/"},
    {id: 159, nome: "EDUCAÇÃO INFANTIL", descricao: "Lecionar para crianças.", link: "https://www.ead.senac.br/pos-graduacao/educacao-infantil/?utm_source=bing&utm_medium=cpc&utm_campaign=P%C3%B3s-gradua%C3%A7%C3%A3o%20EAD%20%C2%A02021%2F1&utm_term=%2Beduca%C3%A7%C3%A3o%20%2Binfantil&utm_content=Educa%C3%A7%C3%A3o%20Infantil"},
    {id: 160, nome: "NANOTECNOLOGIA", descricao: "Desenvolve produtos através de partículas minúsculas.", link: "https://www.guiadacarreira.com.br/profissao/nanotecnologia/"},
    {id: 161, nome: "NEGÓCIOS INTERNACIONAIS", descricao: "Comercialização entre empresas de países diferentes.", link: "https://fae.edu/cursos/66724642/negocios+internacionais.htm"},
    {id: 162, nome: "GESTÃO DE SEGURANÇA PRIVADA", descricao: "Administração de empresas de segurança.", link: "https://www.guiadacarreira.com.br/cursos/gestao-de-seguranca-privada/"},
    {id: 163, nome: "ENGENHARIA URBANA", descricao: "Elaborar projetos em infra-estrutura em geral.", link: "http://www.em.ufop.br/index.php/graduacao?id=307"},
    {id: 164, nome: "ENGENHARIA DE CONTROLE E AUTOMAÇÃO", descricao: "Automatizar processos industriais e equipamentos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-de-controle-e-automacao/"},
    {id: 165, nome: "ENGENHARIA DE SISTEMAS", descricao: "Desenvolver sistemas tecnológicos complexos.", link: "https://www.guiadacarreira.com.br/profissao/engenharia-de-sistemas/"},
    {id: 166, nome: "ENGENHARIA DE PRODUÇÃO", descricao: "Gerenciar recursos e processos para melhora de produtividade.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-de-producao/"},
    {id: 167, nome: "ENGENHARIA DE SEGURANÇA DO TRABALHO", descricao: "Prevenir acidentes de trabalho.", link: "https://blog.ipog.edu.br/engenharia-e-arquitetura/engenharia-de-seguranca-do-trabalho/"},
    {id: 168, nome: "ENGENHARIA CIVIL", descricao: "Elaborar projetos e gerenciar construçõe em geral.", link: "https://www.guiadacarreira.com.br/carreira/engenharia-civil/"},
    {id: 169, nome: "ENGENHARIA DE MATERIAIS", descricao: "Pesquisa e utilização de novos materiais.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-de-materiais/#:~:text=A%20gradua%C3%A7%C3%A3o%20em%20Engenharia%20de,cer%C3%A2mica%2C%20metais%20ou%20pol%C3%ADmeros)"},
    {id: 170, nome: "ENGENHARIA AGRONÔMICA", descricao: "Otimizar a produção de produtos de origem animal e vegetal.", link: "https://www.guiadacarreira.com.br/cursos/engenharia-agronomica/"},
    {id: 171, nome: "ENGENHARIA DE BIOSSISTEMAS", descricao: "Aplicação de tecnologias na produção agropecuária.", link: "https://www.guiadacarreira.com.br/profissao/engenharia-de-biossistemas/"},
    {id: 172, nome: "ENGENHARIA ELÉTRICA", descricao: "Geração, distribuição e instalação de energia elétrica.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-eletrica/"},
    {id: 173, nome: "ENGENHARIA METALÚRGICA", descricao: "Transformação de minérios em metais e ligas metálicas.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-metalurgica/"},
    {id: 174, nome: "ENGENHARIA FÍSICA", descricao: "Aplicação da física nos processos industriais", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-fisica/#:~:text=A%20UFSCar%20foi%20uma%20das,Qu%C3%ADmica%20Tecnol%C3%B3gica%20Geral"},
    {id: 175, nome: "ENGENHARIA DE AQUICULTURA", descricao: "Cultivo em cativeiros de peixes, frutos do mar e plantas.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-de-aquicultura/"},
    {id: 176, nome: "ENGENHARIA DE PESCA", descricao: "Captura, criação e industrialização de organismos aquáticos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-de-pesca/"},
    {id: 177, nome: "ENGENHARIA DE MINAS", descricao: "Prospecção e extração de minérios.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-de-minas/"},
    {id: 178, nome: "ENGENHARIA BIOQUÍMICA", descricao: "Controle de processos biológicos na indústria.", link: "https://www.guiadacarreira.com.br/profissao/engenharia-bioquimica/"},
    {id: 179, nome: "ENGENHARIA DE PETRÓLEO E GÁS", descricao: "Produção de petróleo e gás natural.", link: "https://querobolsa.com.br/cursos-e-faculdades/engenharia-de-petroleo-e-gas"},
    {id: 180, nome: "ENGENHARIA NAVAL", descricao: "Projeto e construção de embarcações.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-naval/"},
    {id: 181, nome: "ENGENHARIA QUÍMICA", descricao: "Transformar matérias-primas em produtos.", link: "https://guiadoestudante.abril.com.br/profissoes/engenharia-quimica-2/"},
    {id: 182, nome: "ENGENHARIA AEROESPACIAL", descricao: "Projeto e fabricação de veículos espaciais (aeronaves, satélites, foguetes).", link: "https://www.guiadacarreira.com.br/carreira/engenharia-aeroespacial/"},
    {id: 183, nome: "ENGENHARIA MECÂNICA", descricao: "Construção e manutenção de máquinas e equipamentos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-mecanica/"},
    {id: 184, nome: "ENGENHARIA INDUSTRIAL", descricao: "Gerenciar recursos necessários para produção industrial.", link: "https://www.guiadacarreira.com.br/cursos/engenharia-industrial/"},
    {id: 185, nome: "ENGENHARIA AERONÁUTICA", descricao: "Projetos e fabricação de aeronaves.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-aeronautica/"},
    {id: 186, nome: "ENGENHARIA DE AGRIMENSURA", descricao: "Medição de espaços territoriais.", link: "https://www.guiadacarreira.com.br/carreira/engenharia-de-agrimensura/"},
    {id: 187, nome: "ENGENHARIA DE HORTICULTURA", descricao: "Plantio de hortifrutigranjeiros.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-de-horticultura/"},
    {id: 188, nome: "ENGENHARIA DE ALIMENTOS", descricao: "Fabricação, armazenamento e distribuição de alimentos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-alimentos/"},
    {id: 189, nome: "ENGENHARIA CARTOGRÁFICA", descricao: "Captar e analisar dados para elaboração de mapas.", link: "https://querobolsa.com.br/cursos-e-faculdades/engenharia-cartografica"},
    {id: 190, nome: "ENGENHARIA MECATRÔNICA", descricao: "Projeto e instalação de equipamentos automatizados (robôs).", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-mecatronica/"},
    {id: 191, nome: "ENGENHARIA DE ENERGIA", descricao: "Planejar e desenvolver sistemas de geração e transmissão de energia.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-energia/"},
    {id: 192, nome: "ENGENHARIA TÊXTIL", descricao: "Produção de fios, tecidos e vestuários.", link: "https://guiadoestudante.abril.com.br/profissoes/engenharia-textil-2/"},
    {id: 193, nome: "ENGENHARIA DE COMPUTAÇÃO", descricao: "Projeto e construção de hardware e software.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-computacao/"},
    {id: 194, nome: "ENGENHARIA DE TELECOMUNICAÇÕES", descricao: "Projeto, instalação de equipamentos de telecomunicações.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-de-telecomunicacoes/"},
    {id: 195, nome: "ENGENHARIA DE INOVAÇÃO", descricao: "Identificar e solucionar demandas de inovação em qualquer área da engenharia.", link: "https://guiadoestudante.abril.com.br/profissoes/engenharia-de-inovacao/"},
    {id: 196, nome: "ENGENHARIA DA COMPLEXIDADE", descricao: "Integra conhecimentos das Engenharias e da Ciência.", link: "https://www.unoeste.br/graduacao/engenharia-complexidade"},
    {id: 197, nome: "ENGENHARIA DE TRANSPORTES E LOGÍSTICA", descricao: "Gerenciar redes de transportes e cadeias de suprimentos.", link: "https://www.universia.net/br/estudios/engenharia-transportes-logistica.0024420.html"},
    {id: 198, nome: "ENGENHARIA FERROVIÁRIA E METROVIÁRIA", descricao: "Projeto e manutenção de ferrovias.", link: "https://www.universia.net/br/estudios/engenharia-ferroviaria-metroviaria.0024421.html"},
    {id: 199, nome: "ENGENHARIA BIOMÉDICA", descricao: "Desenvolver equipamentos médicos e odontológicos.", link: "https://www.guiadacarreira.com.br/carreira/engenharia-biomedica/"},
    {id: 200, nome: "ENGENHARIA ELETRÔNICA", descricao: "Desenvolve componentes e dispositivos eletrônicos.", link: "https://www.guiadacarreira.com.br/profissao/engenharia-eletronica/"},
    {id: 201, nome: "ENGENHARIA BIOTECNOLÓGICA", descricao: "Desenvolve vacinas, inseticidas, clonagem.", link: "https://www.infoescola.com/profissoes/engenharia-de-biotecnologia/"},
    {id: 202, nome: "ENGENHARIA AGRÍCOLA E AMBIENTAL", descricao: "Solução de problemas do sistema agrícola e ambiental.", link: "http://portal.ufvjm.edu.br/a-universidade/cursos/eag"},
    {id: 203, nome: "ENGENHARIA ACÚSTICA", descricao: "Controle de sons e vibrações.", link: "https://guiadoestudante.abril.com.br/profissoes/engenharia-acustica/"},
    {id: 204, nome: "ENGENHARIA DE MOBILIDADE", descricao: "Construção de estradas, ferrovias, portos e aeroportos.", link: "https://engenharia360.com/engenharia/engenharia-da-mobilidade/"},
    {id: 205, nome: "ENGENHARIA AMBIENTAL", descricao: "Projetos de preservação do ar, água e solo.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-ambiental/"},
    {id: 206, nome: "ENGENHARIA SANITÁRIA", descricao: "Projetos de saneamento básico.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-sanitaria/"},
    {id: 207, nome: "ENGENHARIA FLORESTAL", descricao: "Cultivo e produção de bens oriundos da floresta.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-florestal/"},
    {id: 208, nome: "ENGENHARIA DE REDES DE COMUNICAÇÕES", descricao: "Transmissão das informações e dados via computador.", link: "https://querobolsa.com.br/cursos-e-faculdades/engenharia-de-redes-de-comunicacoes"},
    {id: 209, nome: "ENGENHARIA AUTOMOTIVA", descricao: "Projeto e construção de sistemas automotivos.", link: "https://www.guiadacarreira.com.br/profissao/engenharia-automotiva/"},
    {id: 210, nome: "ARTES APLICADAS", descricao: "Criação de peças em cerâmicas.", link: "https://ufsj.edu.br/vestibular/artes_aplicadas_ceramica.php"},
    {id: 211, nome: "ENGENHARIA NUCLEAR", descricao: "Geração e aplicação de energia nuclear.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-nuclear/"},
    {id: 212, nome: "FÍSICA DE MATERIAIS", descricao: "Estuda as propriedades físicas dos materiais.", link: "https://www.universia.net/br/estudios/fisica-materiais.0020222.html"},
    {id: 213, nome: "ENGENHARIA DE SOFTWARE", descricao: "Desenvolvimento de softwares e programas computacionais.", link: "https://querobolsa.com.br/cursos-e-faculdades/engenharia-de-software"},
    {id: 214, nome: "AGRONOMIA", descricao: "Trabalha com plantações e rebanhos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/agronomia/"},
    {id: 215, nome: "ENGENHARIA DE MANUFATURA", descricao: "Fabricação de produtos diversos (automóveis, eletrodomésticos, etc).", link: "http://www.upa.unicamp.br/engenharia-de-manufatura"},
    {id: 216, nome: "GEOFÍSICA", descricao: "Estuda as propriedades físicas e os processos dinâmicos da terra.", link: "https://guiadoestudante.abril.com.br/profissoes/geofisica/"},
    {id: 217, nome: "ENGENHARIA AGRÍCOLA", descricao: "Cuida dos processos de produção agropecuária.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-agricola-2/#:~:text=O%20Engenheiro%20Agr%C3%ADcola%20%C3%A9%20o,e%20a%20polui%C3%A7%C3%A3o%20de%20mananciais"},
    {id: 218, nome: "BIOQUÍMICA", descricao: "Estuda os processos químicos dos organismos vivos.", link: "https://querobolsa.com.br/carreiras-e-profissoes/bioquimico"},
    {id: 219, nome: "MÚSICA ELETRÔNICA", descricao: "Criação, gravação e edição de músicas eletrônicas.", link: "https://portal.anhembi.br/graduacao/cursos/tecnologia-em-producao-fonografica-producao-de-musica-eletronica/#sobre"},
    {id: 220, nome: "ENGENHARIA HÍDRICA", descricao: "Cuidar da exploração e do uso dos recursos hídricos.", link: "https://guiadoestudante.abril.com.br/profissoes/engenharia-hidrica-2/"},
    {id: 221, nome: "ARQUIVOLOGIA", descricao: "Preservação e restauração de documentos.", link: "https://www.guiadacarreira.com.br/carreira/arquivologia/#:~:text=Arquivologia%20%C3%A9%20o%20curso%20que,DVDs%20e%20CDs%2C%20entre%20outros."},
    {id: 222, nome: "ENGENHARIA DE BIOPROCESSOS", descricao: "Processos industriais que envolvem substâncias produzidas por seres vivos.", link: "https://www.guiadacarreira.com.br/guia-das-profissoes/engenharia-de-bioprocessos/"},
    {id: 223, nome: "GESTÃO DE SAÚDE AMBIENTAL", descricao: "Análise e solução de problemas relacionados à saúde pública.", link: "http://www.ig.ufu.br/gestao-em-saude-ambiental/conheca-o-curso"},
]